# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/envoy-example/envoy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod" 
    directory: "/envoy-example/go" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/envoy-example/go"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod" 
    directory: "/envoy-example/init-container" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/envoy-example/init-container"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/nginx-example/nginx"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod" 
    directory: "/nginx-example/go" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/nginx-example/go"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod" 
    directory: "/nginx-example/init-container" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/nginx-example/init-container"
    schedule:
      interval: "weekly"